from playwright.sync_api import expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://localhost:4200/")
    page.locator("[data-test=\"sort\"]").select_option("price,desc")
    page.locator("[data-test=\"sort\"]").select_option("")
    page.locator("[data-test=\"sort\"]").select_option("co2_rating,asc")
    page.locator("[data-test=\"sort\"]").select_option("name,asc")
    page.get_by_role("slider", name="ngx-slider-max").click()
    page.locator(".ngx-slider-span.ngx-slider-bar-wrapper.ngx-slider-full-bar > .ngx-slider-span").click()
    page.get_by_role("slider", name="ngx-slider-max").click()
    page.get_by_role("slider", name="ngx-slider-max").click()
    page.locator(".ngx-slider-span.ngx-slider-bar.ngx-slider-selection").click()
    page.locator(".ngx-slider-span.ngx-slider-bar-wrapper.ngx-slider-full-bar > .ngx-slider-span").click()
    page.locator("[data-test=\"search-query\"]").click()
    page.locator("[data-test=\"search-submit\"]").click()
    page.locator("[data-test=\"search-reset\"]").click()
    page.locator("#filters").get_by_text("Power Tools").click()
    page.locator("#filters").get_by_text("Power Tools").click()
    page.get_by_text("Sander").click()
    page.get_by_text("Sander", exact=True).click()
    page.get_by_text("ForgeFlex Tools").click()
    page.locator("[data-test=\"brand-01KDG94BGG8XGAAZNZA60VME5Z\"]").uncheck()
    page.locator("[data-test=\"category-01KDG94CGJWWFY9THZVJVWGPHH\"]").check()
    page.locator("[data-test=\"category-01KDG94CGJWWFY9THZVJVWGPHH\"]").uncheck()
    page.get_by_text("Sander").click()
    page.locator("[data-test=\"category-01KDG94CGJWWFY9THZVJVWGPHH\"]").uncheck()
    page.get_by_text("Show only eco-friendly").click()
    page.locator("[data-test=\"eco-friendly-filter\"]").uncheck()
    page.locator("[data-test=\"eco-friendly-filter\"]").check()
    expect(page.locator("[data-test=\"product-01KDG94CQC0SHA4A71CT4WPR0P\"]")).to_match_aria_snapshot("- text: ECO")
    expect(page.locator("[data-test=\"product-01KDG94CNH84PRRRYPVCT1CYRA\"] [data-test=\"eco-badge\"]")).to_match_aria_snapshot("- text: ECO")
    expect(page.locator("[data-test=\"product-01KDG94CNH84PRRRYPVCT1CYRA\"] [data-test=\"co2-rating-badge\"]")).to_match_aria_snapshot("- text: B")
    page.get_by_role("button", name="Page-1").click()
    page.get_by_role("button", name="Page-2").click()
    page.get_by_role("button", name="Next").click()
    page.get_by_role("button", name="Page-3").click()
    page.get_by_role("listitem").filter(has_text="«").click()
    page.get_by_role("button", name="Previous").click()
    page.get_by_role("button", name="Page-5").click()
    page.locator("[data-test=\"first-name\"]").click()
    page.locator("[data-test=\"last-name\"]").click()
    page.locator("[data-test=\"dob\"]").click()
    page.locator("[data-test=\"street\"]").click()
    page.locator("[data-test=\"postal_code\"]").click()
    page.locator("[data-test=\"postal_code\"]").click()
    page.locator("[data-test=\"city\"]").click()
    page.locator("[data-test=\"state\"]").click()
    page.locator("[data-test=\"country\"]").select_option("AU")
    page.locator("[data-test=\"phone\"]").click()
    page.locator("[data-test=\"email\"]").click()
    page.locator("[data-test=\"password\"]").click()
    page.get_by_role("button").filter(has_text=re.compile(r"^$")).click()
    page.locator("[data-test=\"register-submit\"]").click()
    page.locator("[data-test=\"password\"]").click()
    page.locator("[data-test=\"password\"]").fill("1")
    page.locator(".strength-bar").click()
    page.locator("[data-test=\"password\"]").click()
    page.locator("[data-test=\"password\"]").fill("1f")
    page.locator(".fill").click()
    page.locator("[data-test=\"password\"]").click()
    page.locator("[data-test=\"password\"]").fill("1f#fgjvwy68bvn!fRR")
    page.locator(".fill").click()
    expect(page.locator("[data-test=\"register-form\"]")).to_match_aria_snapshot("- text: \"Password strength: Weak Moderate Strong Very Strong Excellent\"")
    page.locator(".fill").click()
    page.get_by_role("button").filter(has_text=re.compile(r"^$")).click()
    page.get_by_role("button").filter(has_text=re.compile(r"^$")).click()
    page.locator("[data-test=\"email\"]").click()
    page.locator("[data-test=\"password\"]").click()
    page.locator("[data-test=\"login-form\"] button").click()
    page.locator("[data-test=\"login-form\"] button").click()
    page.locator("[data-test=\"login-submit\"]").click()
    page.locator("[data-test=\"product-01KDG94CN5W4A9ZRNE8K3TPT1G\"]").click()
    page.locator("[data-test=\"product-01KDG94CN5W4A9ZRNE8K3TPT1G\"]").click()
    page.locator("[data-test=\"unit-price\"]").click()
    expect(page.locator("[data-test=\"unit-price\"]")).to_contain_text("11.14")
    page.locator("[data-test=\"product-description\"]").click()
    page.locator("[data-test=\"co2-rating-badge\"]").get_by_text("D").click()
    page.locator("[data-test=\"quantity\"]").click()
    page.locator("[data-test=\"increase-quantity\"]").click()
    page.locator("[data-test=\"quantity\"]").click()
    page.locator("[data-test=\"add-to-cart\"]").click()
    page.get_by_role("alert", name="You can only have one Thor").click()
    page.locator("[data-test=\"decrease-quantity\"]").click()
    page.locator("[data-test=\"add-to-cart\"]").click()
    page.get_by_role("alert", name="Product added to shopping").click()
    expect(page.locator("[data-test=\"cart-quantity\"]")).to_contain_text("1")
    page.locator("[data-test=\"nav-cart\"]").click()
    page.locator("[data-test=\"add-to-cart\"]").click()
    expect(page.get_by_label("You can only have one Thor")).to_contain_text("You can only have one Thor Hammer in the cart.")
    page.locator("[data-test=\"eco-badge\"]").click()
    page.locator("[data-test=\"co2-rating-badge\"]").get_by_text("B").click()
    page.get_by_role("spinbutton", name="Quantity for Thor Hammer").click()
    page.get_by_role("spinbutton", name="Quantity for Workbench with").click()
    page.get_by_text("Eco-Friendly Discount (5%)").click()
    page.get_by_role("row", name="Thor Hammer  Quantity for").locator("[data-test=\"line-price\"]").click()
    page.get_by_text("$356.40").click()
    page.locator("[data-test=\"cart-total\"]").click()
    page.locator("[data-test=\"proceed-1\"]").click()
    page.get_by_text("Hello Jane Doe, you are").click()
    page.locator("[data-test=\"proceed-2\"]").click()
    page.locator("[data-test=\"street\"]").click()
    page.locator("[data-test=\"city\"]").click()
    page.locator("[data-test=\"state\"]").click()
    page.locator("[data-test=\"state\"]").click()
    page.locator("[data-test=\"country\"]").click()
    page.locator("[data-test=\"postal_code\"]").click()
    page.locator("[data-test=\"proceed-3\"]").click()
    page.locator("[data-test=\"payment-method\"]").select_option("credit-card")
    page.locator("[data-test=\"payment-method\"]").select_option("cash-on-delivery")
    page.locator("[data-test=\"payment-method\"]").select_option("credit-card")
    page.locator("[data-test=\"credit_card_number\"]").click()
    page.locator("[data-test=\"credit_card_number\"]").fill("5634247456389541")
    page.locator("[data-test=\"credit_card_number\"]").click()
    page.locator("[data-test=\"credit_card_number\"]").fill("1234-1234-1234-1234")
    page.locator("[data-test=\"expiration_date\"]").click()
    page.locator("[data-test=\"expiration_date\"]").fill("05/2029")
    page.locator("[data-test=\"cvv\"]").click()
    page.locator("[data-test=\"cvv\"]").fill("456")
    page.locator("[data-test=\"card_holder_name\"]").click()
    page.locator("[data-test=\"card_holder_name\"]").fill("jane doe")
    page.locator("[data-test=\"finish\"]").click()
    page.locator("[data-test=\"payment-success-message\"]").click()
    page.locator("[data-test=\"finish\"]").click()
    page.get_by_text("Thor Hammer", exact=True).click()
    expect(page.locator("tbody")).to_contain_text("Thor Hammer")
    expect(page.locator("tbody")).to_contain_text("Workbench with Drawers")
    expect(page.locator("tbody")).to_contain_text("$11.14")
    expect(page.locator("tbody")).to_contain_text("$356.40")
    page.locator("[data-test=\"cart-subtotal\"]").click()
    expect(page.locator("[data-test=\"cart-subtotal\"]")).to_contain_text("$367.54")
    expect(page.locator("[data-test=\"cart-eco-discount\"]")).to_contain_text("- $18.38")
    expect(page.locator("[data-test=\"cart-total\"]")).to_contain_text("$349.16")
    page.locator(".btn.btn-danger").click()
    page.get_by_role("alert", name="Product deleted.").first.click()
    page.get_by_text("Cart1Sign in2Billing").click()
    expect(page.get_by_role("list")).to_match_aria_snapshot("- list:\n  - listitem: Cart 1\n  - listitem: Sign in 2\n  - listitem: Billing Address 3\n  - listitem: Payment 4")
    page.locator(".btn.btn-danger").first.click()
    page.locator(".btn.btn-danger").first.click()
    page.get_by_text("Hello Jane Doe, you are").click()
    expect(page.locator("app-login")).to_contain_text("Hello Jane Doe, you are already logged in. You can proceed to checkout.")
    expect(page.locator("[data-test=\"payment-success-message\"]")).to_contain_text("Payment was successful")